# database.connections.redis
connection: redis

broadcast:
  topic: home_broadcast

# 队列默认配置
default:
  stream_name: home_default_stream
  group_name: home_default_group
  consumer_name: home_default_{hostname}
  stream_limit: 10000

# 延时队列配置
delay:
  connect: mysql
